/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package englishfunny;

import static englishfunny.MainMenu.icon;
import java.awt.Color;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class ChangeUserInfo extends javax.swing.JPanel {

    Color color = new Color(102,204,255);
    Color xcolor = new Color(204,204,204);
    Color coverBack = new Color(153,204,255);
    public ChangeUserInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PasswordField_Password = new javax.swing.JPasswordField();
        PasswordField_PassCom = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextField_Name = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        ChangeAVTButton = new javax.swing.JPanel();
        Text_Changeyouravt = new javax.swing.JLabel();
        AVT = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        Save_Button = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 255));
        jLabel1.setText("Tên hiển thị");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 204, 255));
        jLabel2.setText("Mật khẩu");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        PasswordField_Password.setForeground(new java.awt.Color(51, 204, 255));
        PasswordField_Password.setBorder(null);
        PasswordField_Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordField_PasswordMouseClicked(evt);
            }
        });
        add(PasswordField_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 360, 20));

        PasswordField_PassCom.setForeground(new java.awt.Color(102, 204, 255));
        PasswordField_PassCom.setBorder(null);
        PasswordField_PassCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordField_PassComActionPerformed(evt);
            }
        });
        add(PasswordField_PassCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 360, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 204, 255));
        jLabel3.setText("Nhập lại mật khẩu");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 150, 20));

        jLabel4.setBackground(new java.awt.Color(102, 204, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 255));
        jLabel4.setText("THÔNG TIN CÁ NHÂN");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 255));
        jLabel5.setText("Email");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        TextField_Name.setForeground(new java.awt.Color(51, 204, 255));
        TextField_Name.setBorder(null);
        TextField_Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextField_NameMouseClicked(evt);
            }
        });
        TextField_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_NameActionPerformed(evt);
            }
        });
        add(TextField_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 350, 30));

        Email.setForeground(new java.awt.Color(51, 204, 255));
        Email.setBorder(null);
        Email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmailMouseClicked(evt);
            }
        });
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 360, 30));

        ChangeAVTButton.setBackground(new java.awt.Color(102, 204, 255));
        ChangeAVTButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangeAVTButtonMouseClicked(evt);
            }
        });

        Text_Changeyouravt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Text_Changeyouravt.setForeground(new java.awt.Color(255, 255, 255));
        Text_Changeyouravt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text_Changeyouravt.setText("Thay đổi avatar");
        Text_Changeyouravt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout ChangeAVTButtonLayout = new javax.swing.GroupLayout(ChangeAVTButton);
        ChangeAVTButton.setLayout(ChangeAVTButtonLayout);
        ChangeAVTButtonLayout.setHorizontalGroup(
            ChangeAVTButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Text_Changeyouravt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ChangeAVTButtonLayout.setVerticalGroup(
            ChangeAVTButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChangeAVTButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Text_Changeyouravt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(ChangeAVTButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 100, 30));
        add(AVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 190, 280));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 330, 10));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 330, 10));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 330, 10));

        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 330, 10));

        Save_Button.setBackground(new java.awt.Color(102, 204, 255));
        Save_Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Save_Button.setForeground(new java.awt.Color(255, 255, 255));
        Save_Button.setText("LƯU");
        Save_Button.setBorder(null);
        Save_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Save_ButtonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Save_ButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Save_ButtonMouseReleased(evt);
            }
        });
        Save_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_ButtonActionPerformed(evt);
            }
        });
        add(Save_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 80, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordField_PassComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordField_PassComActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordField_PassComActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void TextField_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_NameActionPerformed

    private void TextField_NameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextField_NameMouseClicked
        TextField_Name.setText("");
        TextField_Name.setForeground(color);
    }//GEN-LAST:event_TextField_NameMouseClicked

    private void EmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailMouseClicked
        Email.setText("");
        Email.setForeground(color);
    }//GEN-LAST:event_EmailMouseClicked

    private void Save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_ButtonActionPerformed
        try{
            UserDAO userDAO = new UserDAO();
            String fullname = TextField_Name.getText();
            String email = Email.getText();
            String password = PasswordField_Password.getText();
            String Cpassword = PasswordField_PassCom.getText();

            if(password.equals(Cpassword) == false){
                JOptionPane.showMessageDialog(this,"Chưa đồng bộ mật khẩu");
                return;
            }

            
            UserModel userC = new UserModel(EnglishFunnyFrame.scene.user.getID(), EnglishFunnyFrame.scene.user.getUserName(), Cpassword,email, " ", fullname, 0 );
            EnglishFunnyFrame.scene.user = userC;
            userDAO.updateUser(userC);
            
        } catch (SQLException ex) {
            Logger.getLogger(ChangeUserInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Save_ButtonActionPerformed

    private void Save_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Save_ButtonMouseClicked
        JOptionPane.showMessageDialog(this, "Lưu thông tin thành công");
        EnglishFunnyFrame.scene.changeinfor.Init();
        EnglishFunnyFrame.scene.mainmenu.Init();
        EnglishFunnyFrame.scene.mainmenu.setVisible(true);
        
    }//GEN-LAST:event_Save_ButtonMouseClicked

    private void ChangeAVTButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeAVTButtonMouseClicked
        JOptionPane.showMessageDialog(this, "Nâng cấp tài khoản VIP để sử dụng tính năng này!");
    }//GEN-LAST:event_ChangeAVTButtonMouseClicked

    private void Save_ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Save_ButtonMousePressed
        Save_Button.setBackground(coverBack);
    }//GEN-LAST:event_Save_ButtonMousePressed

    private void Save_ButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Save_ButtonMouseReleased
        Save_Button.setBackground(color);
    }//GEN-LAST:event_Save_ButtonMouseReleased

    private void PasswordField_PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordField_PasswordMouseClicked
        PasswordField_Password.setText("");
        PasswordField_Password.setForeground(color);
    }//GEN-LAST:event_PasswordField_PasswordMouseClicked
    public void Init(){
   
        AVT.setText("");
        icon = EnglishFunnyFrame.scene.avatar[EnglishFunnyFrame.scene.user.getAvtID()];
        Image scaled = EnglishFunnyFrame.scene.scaleImage(icon.getImage(), AVT.getWidth(), AVT.getHeight());
        ImageIcon scaledIcon = new ImageIcon(scaled);
        AVT.setIcon(scaledIcon);
        
        TextField_Name.setForeground(xcolor);
        TextField_Name.setText(EnglishFunnyFrame.scene.user.getFullName());
        
        Email.setForeground(xcolor);
        Email.setText(EnglishFunnyFrame.scene.user.getEmail());
        
        PasswordField_Password.setForeground(xcolor);
        PasswordField_PassCom.setForeground(xcolor);
        PasswordField_PassCom.setText(EnglishFunnyFrame.scene.user.getPassWord());
        PasswordField_Password.setText(EnglishFunnyFrame.scene.user.getPassWord());
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AVT;
    private javax.swing.JPanel ChangeAVTButton;
    private javax.swing.JTextField Email;
    private javax.swing.JPasswordField PasswordField_PassCom;
    private javax.swing.JPasswordField PasswordField_Password;
    private javax.swing.JButton Save_Button;
    private javax.swing.JTextField TextField_Name;
    private javax.swing.JLabel Text_Changeyouravt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables

    
}
