/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package englishfunny;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author Administrator
 */
public class MainMenu extends javax.swing.JPanel {

    Color color = new Color(102,204,255);
    Color coverBack = new Color(153,204,255);
    public static ImageIcon icon = new ImageIcon();
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Avatar = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        CoverF = new javax.swing.JPanel();
        FlashCard = new javax.swing.JLabel();
        CoverL = new javax.swing.JPanel();
        Learn = new javax.swing.JLabel();
        CoverT = new javax.swing.JPanel();
        Test = new javax.swing.JLabel();
        CoverUsername = new javax.swing.JPanel();
        UserNameText = new javax.swing.JLabel();
        Update = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        text = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 600));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255)));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 600));

        Exit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Exit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Public\\Pictures\\ICON CỰC MẠNH\\1x\\outline_logout_white_24dp.png")); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        CoverF.setBackground(new java.awt.Color(102, 204, 255));

        FlashCard.setBackground(new java.awt.Color(255, 255, 255));
        FlashCard.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FlashCard.setForeground(new java.awt.Color(255, 255, 255));
        FlashCard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FlashCard.setIcon(new javax.swing.ImageIcon("C:\\Users\\Public\\Pictures\\ICON CỰC MẠNH\\1x\\outline_sticky_note_2_white_24dp.png")); // NOI18N
        FlashCard.setText("FLASH CARD");
        FlashCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlashCardMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FlashCardMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                FlashCardMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout CoverFLayout = new javax.swing.GroupLayout(CoverF);
        CoverF.setLayout(CoverFLayout);
        CoverFLayout.setHorizontalGroup(
            CoverFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoverFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FlashCard, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        CoverFLayout.setVerticalGroup(
            CoverFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CoverFLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(FlashCard, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        CoverL.setBackground(new java.awt.Color(102, 204, 255));

        Learn.setBackground(new java.awt.Color(255, 255, 255));
        Learn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Learn.setForeground(new java.awt.Color(255, 255, 255));
        Learn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Learn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Public\\Pictures\\ICON CỰC MẠNH\\1x\\outline_chrome_reader_mode_white_24dp.png")); // NOI18N
        Learn.setText("HỌC BÀI");
        Learn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LearnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LearnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LearnMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout CoverLLayout = new javax.swing.GroupLayout(CoverL);
        CoverL.setLayout(CoverLLayout);
        CoverLLayout.setHorizontalGroup(
            CoverLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoverLLayout.createSequentialGroup()
                .addComponent(Learn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CoverLLayout.setVerticalGroup(
            CoverLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Learn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        CoverT.setBackground(new java.awt.Color(102, 204, 255));

        Test.setBackground(new java.awt.Color(255, 255, 255));
        Test.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Test.setForeground(new java.awt.Color(255, 255, 255));
        Test.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Test.setIcon(new javax.swing.ImageIcon("C:\\Users\\Public\\Pictures\\ICON CỰC MẠNH\\1x\\outline_fact_check_white_24dp.png")); // NOI18N
        Test.setText("TEST");
        Test.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TestMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TestMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TestMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout CoverTLayout = new javax.swing.GroupLayout(CoverT);
        CoverT.setLayout(CoverTLayout);
        CoverTLayout.setHorizontalGroup(
            CoverTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoverTLayout.createSequentialGroup()
                .addComponent(Test, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CoverTLayout.setVerticalGroup(
            CoverTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoverTLayout.createSequentialGroup()
                .addComponent(Test, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        CoverUsername.setBackground(new java.awt.Color(102, 204, 255));

        UserNameText.setBackground(new java.awt.Color(255, 255, 255));
        UserNameText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UserNameText.setForeground(new java.awt.Color(255, 255, 255));
        UserNameText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserNameText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserNameTextMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserNameTextMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                UserNameTextMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout CoverUsernameLayout = new javax.swing.GroupLayout(CoverUsername);
        CoverUsername.setLayout(CoverUsernameLayout);
        CoverUsernameLayout.setHorizontalGroup(
            CoverUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoverUsernameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CoverUsernameLayout.setVerticalGroup(
            CoverUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserNameText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        Update.setIcon(new javax.swing.ImageIcon("C:\\Users\\Public\\Pictures\\ICON CỰC MẠNH\\icons8-vip-30.png")); // NOI18N
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
        });

        Main.setBackground(new java.awt.Color(102, 204, 255));
        Main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MainMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MainMouseReleased(evt);
            }
        });

        text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text.setText("TRANG CHỦ");

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(text)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CoverL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CoverT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CoverF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Avatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CoverUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(Update)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CoverUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CoverF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CoverL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CoverT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(Exit)
                .addGap(37, 37, 37))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 200, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    }//GEN-LAST:event_formMouseClicked

    private void UserNameTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserNameTextMouseClicked
        EnglishFunnyFrame.scene.learnMenu.setVisible(false);
        EnglishFunnyFrame.scene.flashcard.setVisible(false);
        EnglishFunnyFrame.scene.chart.setVisible(false);
        EnglishFunnyFrame.scene.learn.setVisible(false);
        EnglishFunnyFrame.scene.testMenu.setVisible(false);
        EnglishFunnyFrame.scene.changeinfor.Init();
        EnglishFunnyFrame.scene.changeinfor.setVisible(true);
    }//GEN-LAST:event_UserNameTextMouseClicked

    private void FlashCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlashCardMouseClicked
        EnglishFunnyFrame.scene.learnMenu.setVisible(false);
        EnglishFunnyFrame.scene.chart.setVisible(false);
        EnglishFunnyFrame.scene.learn.setVisible(false);
        EnglishFunnyFrame.scene.testMenu.setVisible(false);
        EnglishFunnyFrame.scene.changeinfor.setVisible(false);
        EnglishFunnyFrame.scene.flashcard.setVisible(true);
        EnglishFunnyFrame.scene.flashcard.Init();
        
    }//GEN-LAST:event_FlashCardMouseClicked

    private void LearnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnMouseClicked
        EnglishFunnyFrame.scene.learn.setVisible(false);
        EnglishFunnyFrame.scene.chart.setVisible(false);
        EnglishFunnyFrame.scene.testMenu.setVisible(false);
        EnglishFunnyFrame.scene.changeinfor.setVisible(false);
        EnglishFunnyFrame.scene.flashcard.setVisible(false);
        EnglishFunnyFrame.scene.learnMenu.setVisible(true);

    }//GEN-LAST:event_LearnMouseClicked

    private void TestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TestMouseClicked
        EnglishFunnyFrame.scene.learnMenu.setVisible(false);
        EnglishFunnyFrame.scene.chart.setVisible(false);
        EnglishFunnyFrame.scene.changeinfor.setVisible(false);
        EnglishFunnyFrame.scene.flashcard.setVisible(false);
        EnglishFunnyFrame.scene.learn.setVisible(false);
        EnglishFunnyFrame.scene.testMenu.setVisible(true);
        

    }//GEN-LAST:event_TestMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        int choice = JOptionPane.showConfirmDialog(this,"Bạn có muốn thoát không","THOÁT",JOptionPane.YES_NO_OPTION);
        switch(choice){
            case JOptionPane.YES_OPTION:
            EnglishFunnyFrame.scene.learnMenu.setVisible(false);
            EnglishFunnyFrame.scene.chart.setVisible(false);
            EnglishFunnyFrame.scene.changeinfor.setVisible(false);
            EnglishFunnyFrame.scene.flashcard.setVisible(false);
            EnglishFunnyFrame.scene.learn.setVisible(false);
            EnglishFunnyFrame.scene.testMenu.setVisible(false);
            EnglishFunnyFrame.scene.mainmenu.setVisible(false);
            EnglishFunnyFrame.scene.welcomeLEFT.setVisible(true);
            EnglishFunnyFrame.scene.signin.setVisible(true);
            EnglishFunnyFrame.scene.signin.Init();
            case JOptionPane.NO_OPTION:
            return;
            
        }
    }//GEN-LAST:event_ExitMouseClicked

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        int choice = JOptionPane.showConfirmDialog(this, "Nâng cấp tải khoản VIP với chỉ 999$/tháng !", "NÂNG CẤP",JOptionPane.YES_OPTION);
        switch(choice){
            case JOptionPane.YES_OPTION:
            JOptionPane.showMessageDialog(this,"Chuyển AirPay đến số điện thoại 0961845202 và làm theo hướng dẫn");
            case JOptionPane.NO_OPTION:
            return;
        }
        
    }//GEN-LAST:event_UpdateMouseClicked

    private void FlashCardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlashCardMousePressed
        CoverF.setBackground(coverBack);
    }//GEN-LAST:event_FlashCardMousePressed

    private void FlashCardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlashCardMouseReleased
        CoverF.setBackground(color);
    }//GEN-LAST:event_FlashCardMouseReleased

    private void LearnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnMousePressed
        CoverL.setBackground(coverBack);
    }//GEN-LAST:event_LearnMousePressed

    private void LearnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnMouseReleased
        CoverL.setBackground(color);
    }//GEN-LAST:event_LearnMouseReleased

    private void TestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TestMousePressed
        CoverT.setBackground(coverBack);
    }//GEN-LAST:event_TestMousePressed

    private void TestMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TestMouseReleased
        CoverT.setBackground(color);
    }//GEN-LAST:event_TestMouseReleased

    private void UserNameTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserNameTextMousePressed
        CoverUsername.setBackground(coverBack);
    }//GEN-LAST:event_UserNameTextMousePressed

    private void UserNameTextMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserNameTextMouseReleased
        CoverUsername.setBackground(color);
    }//GEN-LAST:event_UserNameTextMouseReleased

    private void MainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainMousePressed
        Main.setBackground(coverBack);
    }//GEN-LAST:event_MainMousePressed

    private void MainMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainMouseReleased
        Main.setBackground(color);
    }//GEN-LAST:event_MainMouseReleased

    private void MainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainMouseClicked
        EnglishFunnyFrame.scene.flashcard.setVisible(false);
        EnglishFunnyFrame.scene.learnMenu.setVisible(false);
        EnglishFunnyFrame.scene.learn.setVisible(false);
        EnglishFunnyFrame.scene.testMenu.setVisible(false);
        EnglishFunnyFrame.scene.write.setVisible(false);
        EnglishFunnyFrame.scene.chart.setVisible(true);
    }//GEN-LAST:event_MainMouseClicked
    public void Init(){
   
        Avatar.setText("");
        icon = EnglishFunnyFrame.scene.avatar[EnglishFunnyFrame.scene.user.getAvtID()];
        Image scaled = EnglishFunnyFrame.scene.scaleImage(icon.getImage(), Avatar.getWidth(), Avatar.getHeight());
        ImageIcon scaledIcon = new ImageIcon(scaled);
        Avatar.setIcon(scaledIcon);
        
        UserNameText.setText(EnglishFunnyFrame.scene.user.getFullName());
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Avatar;
    private javax.swing.JPanel CoverF;
    private javax.swing.JPanel CoverL;
    private javax.swing.JPanel CoverT;
    private javax.swing.JPanel CoverUsername;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel FlashCard;
    private javax.swing.JLabel Learn;
    private javax.swing.JPanel Main;
    private javax.swing.JLabel Test;
    private javax.swing.JLabel Update;
    private javax.swing.JLabel UserNameText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables

   
}
