/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package englishfunny;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class Signup extends javax.swing.JPanel {

    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Text_Signin = new javax.swing.JLabel();
        Text_Fullname = new javax.swing.JLabel();
        Text_Password = new javax.swing.JLabel();
        Line_Name = new javax.swing.JSeparator();
        Line_Password = new javax.swing.JSeparator();
        TextField_Name = new javax.swing.JTextField();
        PasswordField_Password = new javax.swing.JPasswordField();
        Button_Signin = new javax.swing.JButton();
        Text_Choose = new javax.swing.JLabel();
        Button_Signup = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setBackground(new java.awt.Color(102, 204, 255));

        Text_Signin.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Text_Signin.setForeground(new java.awt.Color(255, 255, 255));
        Text_Signin.setText("ĐĂNG NHẬP");

        Text_Fullname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Text_Fullname.setForeground(new java.awt.Color(255, 255, 255));
        Text_Fullname.setText("TÊN ĐĂNG NHẬP");

        Text_Password.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Text_Password.setForeground(new java.awt.Color(255, 255, 255));
        Text_Password.setText("MẬT KHẨU");

        TextField_Name.setBackground(new java.awt.Color(102, 204, 255));
        TextField_Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextField_Name.setForeground(new java.awt.Color(255, 255, 255));
        TextField_Name.setBorder(null);
        TextField_Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextField_NameMouseClicked(evt);
            }
        });
        TextField_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_NameActionPerformed(evt);
            }
        });

        PasswordField_Password.setBackground(new java.awt.Color(102, 204, 255));
        PasswordField_Password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PasswordField_Password.setForeground(new java.awt.Color(255, 255, 255));
        PasswordField_Password.setBorder(null);
        PasswordField_Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordField_PasswordMouseClicked(evt);
            }
        });
        PasswordField_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordField_PasswordActionPerformed(evt);
            }
        });

        Button_Signin.setBackground(new java.awt.Color(255, 255, 255));
        Button_Signin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_Signin.setForeground(new java.awt.Color(102, 204, 255));
        Button_Signin.setText("Đăng nhập");
        Button_Signin.setBorder(null);
        Button_Signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_SigninMouseClicked(evt);
            }
        });
        Button_Signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SigninActionPerformed(evt);
            }
        });

        Text_Choose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text_Choose.setForeground(new java.awt.Color(255, 255, 255));
        Text_Choose.setText("hoặc nếu bạn KHÔNG có tài khoản");

        Button_Signup.setBackground(new java.awt.Color(255, 255, 255));
        Button_Signup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_Signup.setForeground(new java.awt.Color(102, 204, 255));
        Button_Signup.setText("Đăng ký");
        Button_Signup.setBorder(null);
        Button_Signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_SignupMouseClicked(evt);
            }
        });
        Button_Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 107, Short.MAX_VALUE)
                .addComponent(Text_Signin, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Line_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(Text_Password)
                            .addComponent(Text_Fullname)
                            .addComponent(Line_Name)
                            .addComponent(TextField_Name)
                            .addComponent(PasswordField_Password)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(Button_Signin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Text_Choose)
                                .addGap(18, 18, 18)))
                        .addComponent(Button_Signup, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(Text_Signin)
                .addGap(36, 36, 36)
                .addComponent(Text_Fullname)
                .addGap(18, 18, 18)
                .addComponent(TextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Line_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Text_Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Line_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Button_Signin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_Choose)
                    .addComponent(Button_Signup, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SignupActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_Button_SignupActionPerformed

    private void TextField_NameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextField_NameMouseClicked

        if(TextField_Name.equals(" ")) TextField_Name.setText("Bạn chưa điền tên đăng nhập");
    }//GEN-LAST:event_TextField_NameMouseClicked

    private void PasswordField_PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordField_PasswordMouseClicked
        PasswordField_Password.setText("");
    }//GEN-LAST:event_PasswordField_PasswordMouseClicked

    private void Button_SigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SigninActionPerformed
        UserDAO userDAO = new UserDAO();
        String username = TextField_Name.getText();
        String password = PasswordField_Password.getText();
        
        UserModel usermodel = userDAO.selectUser(username);
        if(username.equals("") && password.equals("")){
            JOptionPane.showMessageDialog(this,"Bạn hãy đăng nhập!");
            return;
        }
        if(usermodel == null){
            JOptionPane.showMessageDialog(this,"Tài khoản không tồn tại");
            return;
        }
        if(usermodel.getPassWord().equals(password)){
            EnglishFunnyFrame.scene.user = usermodel;
            EnglishFunnyFrame.scene.mainmenu.Init();
            
        }
        
        else{
            JOptionPane.showMessageDialog(this,"Tài khoản không tồn tại");
            return;
        }
        
    }//GEN-LAST:event_Button_SigninActionPerformed

    private void Button_SignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SignupMouseClicked
        EnglishFunnyFrame.scene.signin.setVisible(false);
        EnglishFunnyFrame.scene.signup.setVisible(true);
        EnglishFunnyFrame.scene.signup.Init();
        
              
    }//GEN-LAST:event_Button_SignupMouseClicked

    private void PasswordField_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordField_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordField_PasswordActionPerformed

    private void Button_SigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SigninMouseClicked
        JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
        EnglishFunnyFrame.scene.welcomeLEFT.setVisible(false);
        EnglishFunnyFrame.scene.signin.setVisible(false);
        EnglishFunnyFrame.scene.mainmenu.setVisible(true);
        EnglishFunnyFrame.scene.chart.setVisible(true);
        
    }//GEN-LAST:event_Button_SigninMouseClicked
    public void Init(){
        TextField_Name.setText("");
        PasswordField_Password.setText("");
    }
    private void TextField_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_NameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Signin;
    private javax.swing.JButton Button_Signup;
    private javax.swing.JSeparator Line_Name;
    private javax.swing.JSeparator Line_Password;
    private javax.swing.JPasswordField PasswordField_Password;
    private javax.swing.JTextField TextField_Name;
    private javax.swing.JLabel Text_Choose;
    private javax.swing.JLabel Text_Fullname;
    private javax.swing.JLabel Text_Password;
    private javax.swing.JLabel Text_Signin;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
